language: go
go:
  - 1.20
  - master

env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
script:
  - go test -v ./...

install:
notifications:
  email:
    on_success: change
    on_failure: always
