Name: Storage
Dev: true

IpAddr: 192.168.1.119
RpcPort: :9011
HttpPort: :9001

ServiceType: "storage"

Group : "Local-1"

DriverName: "Local"
DriverAddtion:
  RootPath : ./storage-1

DBdir : LevelDbdata-storage1
FileSizeLimit: 10240000

Trackers:
  - http://192.168.1.119:8001

Log:
  ServiceName: storage-local
  OutPath: ./logs/storage-1.log