Name: Storage
ListenOn: 127.0.0.1:9001
Dev: true

ServiceType: "storage"

Group : "Local-1"

DriverName: "Local"
DriverAddtion:
  RootPath : ./storage-1

DBdir : LevelDbdata-storage1
FileSizeLimit: 1024000

Trackers:
  - http://127.0.0.1:8001

Log:
  ServiceName: storage-local
  OutPath: ./logs/storage-1.log