Name: Storage
ListenOn: 0.0.0.0:9002


ServiceType: "tracker"

Mode: dev

Log:
  ServiceName: storage-rpc
  Level: debug
  Encoding: plain

Storages :
  - AliyundriveOpen:
      authTokenURL : djsakl1321
  - 115Driver:
      QRCodeToken: djsklajd1312

LevelDb:
  storeRoot: ./data

DriverConfig :
  TimeOut: 10000
  HeartBeat: 60000


Etcd:
  Hosts:
  - etcd:2379
  Key: storage.rpc

TrackerRpc:
  ListenOn: localhost:8001
  Etcd:
    Hosts:
    - localhost:2379
    Key: tacker.rpc